services:
  nginx:
    container_name: api-gateway-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/etc/nginx/
      - ./logs:/var/log/nginx
    restart: unless-stopped
    command: >
      bash -c "/etc/nginx/nginx-reload.sh & nginx -g 'daemon off;'"
